# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import api_keys

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
load_csv = "../output_data/cities_FINAL.csv"
cities = pd.read_csv(load_csv)
cities.drop(labels='Unnamed: 0', axis = 1, inplace = True)
cities.head()

,City,Country,Lat,Lng,Max Temp (Celsius),Humidity %,Cloudiness %,Wind Speed (kmph),Date
0,Ardakān,IR,32.3100,54.0175,16.00,25,0,1.03,2021-04-20 02:23:52
1,Vaini,TO,-21.2000,-175.2000,29.00,70,20,5.14,2021-04-20 02:20:04
2,Nizhneangarsk,RU,55.7833,109.5500,-1.51,88,100,4.36,2021-04-20 02:23:55
3,Jamestown,US,42.0970,-79.2353,9.44,87,90,2.57,2021-04-20 02:23:57
4,Loknya,RU,56.8300,30.1467,6.20,73,100,2.30,2021-04-20 02:23:58

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [13]:
locations = cities[["Lat", "Lng"]]
humidity = cities["Humidity %"]
gmaps.configure(api_key=g_key)

figure_layout = {
    'width': '800px',
    'height': '500px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

cities_humidity = gmaps.figure(layout=figure_layout)
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 100, point_radius = 2)
cities_humidity.add_layer(heat_layer)

In [14]:
cities_humidity

Figure(layout=FigureLayout(border='1px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [26]:
#copy df and amend with conditionals:
# A max temperature lower than 80 degrees but higher than 70 - i.e. not equal to either 80 or 70 (Fahrenheit) therefore conversion to celcius required
# Wind speed less than 10 mph.
# Zero cloudiness.
# Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

cities_ideal = cities
cities_ideal = cities_ideal[cities_ideal['Max Temp (Celsius)'] < ((80-32)/1.8)]
cities_ideal = cities_ideal[cities_ideal['Max Temp (Celsius)'] > ((70-32)/1.8)]
cities_ideal = cities_ideal[cities_ideal['Wind Speed (kmph)'] < 10]
cities_ideal = cities_ideal[cities_ideal['Cloudiness %'] == 0]
cities_ideal = cities_ideal.dropna()
cities_ideal = cities_ideal.reset_index()
cities_ideal.drop(labels = 'index', axis = 1, inplace = True)
cities_ideal

,City,Country,Lat,Lng,Max Temp (Celsius),Humidity %,Cloudiness %,Wind Speed (kmph),Date
0,Cockburn Town,TC,21.4612,-71.1419,25.86,85,0,6.47,2021-04-20 02:26:26
1,Yulara,AU,-25.2406,130.9889,23.00,18,0,5.14,2021-04-20 02:27:20
2,Aquin,HT,18.2833,-73.4000,24.93,83,0,3.15,2021-04-20 02:28:02
3,Ballina,AU,-28.8667,153.5667,25.00,38,0,4.63,2021-04-20 02:28:34
4,Carnarvon,AU,-24.8667,113.6333,25.38,41,0,8.85,2021-04-20 02:19:34
5,Alice Springs,AU,-23.7000,133.8833,23.33,18,0,4.63,2021-04-20 02:29:35
6,Sahuaripa,MX,29.0500,-109.2333,21.72,16,0,1.94,2021-04-20 02:30:54
7,Namie,JP,37.4833,141.0000,21.67,26,0,1.34,2021-04-20 02:30:16
8,Doha,QA,25.2867,51.5333,25.00,33,0,3.32,2021-04-20 02:35:08
9,Pasni,PK,25.2631,63.4710,26.08,52,0,3.49,2021-04-20 02:37:05
10,Shunyi,CN,40.1250,116.6453,25.56,46,0,3.00,2021-04-20 02:41:00
11,Salalah,OM,17.0151,54.0924,26.00,61,0,3.09,2021-04-20 02:36:48
12,Maceió,BR,-9.6658,-35.7353,23.00,100,0,1.03,2021-04-20 02:41:40
13,Taoudenni,ML,22.6783,-3.9836,25.34,13,0,4.82,2021-04-20 02:42:25

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [27]:
hotel_df = cities_ideal
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Lat,Lng,Max Temp (Celsius),Humidity %,Cloudiness %,Wind Speed (kmph),Date,Hotel Name
0,Cockburn Town,TC,21.4612,-71.1419,25.86,85,0,6.47,2021-04-20 02:26:26,
1,Yulara,AU,-25.2406,130.9889,23.00,18,0,5.14,2021-04-20 02:27:20,
2,Aquin,HT,18.2833,-73.4000,24.93,83,0,3.15,2021-04-20 02:28:02,
3,Ballina,AU,-28.8667,153.5667,25.00,38,0,4.63,2021-04-20 02:28:34,
4,Carnarvon,AU,-24.8667,113.6333,25.38,41,0,8.85,2021-04-20 02:19:34,
5,Alice Springs,AU,-23.7000,133.8833,23.33,18,0,4.63,2021-04-20 02:29:35,
6,Sahuaripa,MX,29.0500,-109.2333,21.72,16,0,1.94,2021-04-20 02:30:54,
7,Namie,JP,37.4833,141.0000,21.67,26,0,1.34,2021-04-20 02:30:16,
8,Doha,QA,25.2867,51.5333,25.00,33,0,3.32,2021-04-20 02:35:08,
9,Pasni,PK,25.2631,63.4710,26.08,52,0,3.49,2021-04-20 02:37:05,
10,Shunyi,CN,40.1250,116.6453,25.56,46,0,3.00,2021-04-20 02:41:00,
11,Salalah,OM,17.0151,54.0924,26.00,61,0,3.09,2021-04-20 02:36:48,
12,Maceió,BR,-9.6658,-35.7353,23.00,100,0,1.03,2021-04-20 02:41:40,
13,Taoudenni,ML,22.6783,-3.9836,25.34,13,0,4.82,2021-04-20 02:42:25,

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure